version: '3.4'

services:

  trainingsheetdb:
    image: postgres

  pgadmin:
    image: dpage/pgadmin4

  portainer:
    image: portainer/portainer-ce

  mytrainingsheet.api:
    image: ${DOCKER_REGISTRY-}mytrainingsheetapi
    build:
      context: .
      dockerfile: src/MyTrainingSheet.Api/Dockerfile

volumes:
  portainer_data:
  postgres_data:
  pgadmin_data: